In [48]:
import pandas as pd 
import time 
import re
import numpy as np

In [68]:
#Input path
path_tablajose = 'C:/Users/paula/OneDrive/Documentos/0. Master Biologia Computacional UPM/TFM_CNB/Automatizated process v2/Tables/DatabaseSamplesJOSE.csv'
path_tablasra = 'C:/Users/paula/OneDrive/Documentos/0. Master Biologia Computacional UPM/TFM_CNB/Automatizated process v2/Tables/SraRunInfo.csv'
path_tablaweb = 'C:/Users/paula/OneDrive/Documentos/0. Master Biologia Computacional UPM/TFM_CNB/Automatizated process v2/Tables/SRAinformation.tsv'
path_tablaena = 'C:/Users/paula/OneDrive/Documentos/0. Master Biologia Computacional UPM/TFM_CNB/Automatizated process v2/Tables/definitivo.txt'
path_infotable = 'C:/Users/paula/OneDrive/Documentos/0. Master Biologia Computacional UPM/TFM_CNB/Automatizated process v2/Tables/sra_result.csv'
#Upload files
dfjose = pd.read_csv(path_tablajose)
dfsra = pd.read_csv(path_tablasra)
dfena = pd.read_csv(path_tablaena, sep ='\t')
dfweb = pd.read_csv(path_tablaweb,sep='\t')
dfinfo = pd.read_csv(path_infotable)

C:\Users\paula\AppData\Local\Temp\ipykernel_8276\3265156387.py:9: DtypeWarning: Columns (40) have mixed types. Specify dtype option on import or set low_memory=False.
  dfsra = pd.read_csv(path_tablasra)

In [33]:
print(len(dfjose))
print(len(dfsra))
print(len(dfena))

28123
94106
87007

In [69]:
# Merge con ENA
dfena.rename(columns = {'run_accession':'Run'}, inplace = True)
dfsra =  pd.merge(dfsra, dfena, how='outer', on='Run')
gsm_dic = {}

for index, row in dfsra.iterrows():
    exp = row['Experiment']
    gsm = row['SampleName']
    gsm_dic[gsm] = exp
for index, row in dfsra.iterrows():
    exp = row['experiment_accession']
    gsm = row['run_alias']
    gsm_dic[gsm] = exp
#     if gsm in gsm_dic:
#         gsm_dic[gsm].append(exp)
#     else:
#         gsm_dic[gsm] = exp
        
for index, row in dfjose.iterrows():
    if 'GSM' in row.Experiment:
        try:
            dfjose['Experiment'] = dfjose['Experiment'].replace(row.Experiment, gsm_dic[row.Experiment])
#             gsm_dic[row.Experiment]
        except:
            print(row.Experiment)
            
#Merge con Jose
for index, row in dfsra.iterrows():
    if row['experiment_accession']!=row['Experiment']:
        dfsra['Experiment'] = dfsra['Experiment'].replace(row.Experiment, row.experiment_accession)

# dfsra =  pd.merge(dfsra, dfjose, how='outer', on='Experiment')

GSM1692581
GSM1692582
GSM1692583
GSM1692584
GSM1692585
GSM1692586
GSM1835604
GSM1835605
GSM1835606
GSM1835607
GSM1835608
GSM1835609
GSM1835610
GSM1835611
GSM277612
GSM277613
GSM277614
GSM277615
GSM1835574
GSM1835575
GSM1835576
GSM1835577
GSM1835578
GSM1835579
GSM1835580
GSM1835581
GSM1835582
GSM1835583
GSM1835584
GSM1835585
GSM1835586
GSM1835587
GSM1835588
GSM1835589
GSM1835590
GSM1835591
GSM1835592
GSM1835593
GSM1835594
GSM1835595
GSM1835596
GSM1835597
GSM1835598
GSM1835599
GSM1835600
GSM1835601
GSM1835602
GSM1835603
GSM1635139
GSM1635141
GSM1635143
GSM1635145
GSM1818909
GSM1818910
GSM1818911
GSM1818912
GSM1818913
GSM1818914
GSM1818915
GSM1818916
GSM1818917
GSM1818918
GSM1818919
GSM1818920
GSM1818921
GSM1818922
GSM1818923
GSM1818924
GSM1818925
GSM1818926
GSM1818927
GSM1818928
GSM1818929
GSM1818930
GSM1818931
GSM1818932
GSM1818933
GSM1818934
GSM1818935
GSM1818936
GSM1818937
GSM1818938
GSM1818939
GSM1818940
GSM1818941
GSM1818942
GSM1818943
GSM1818944
GSM1818945
GSM1818946
GSM1818947
GSM1818948
GSM1818949
GSM1818950
GSM1818951
GSM1818952
GSM1818953
GSM1818954
GSM1818955
GSM1818956
GSM1818957
GSM1818958
GSM1818959
GSM1818960
GSM1818961
GSM1818962
GSM1818963
GSM1818964
GSM1818965
GSM1818966
GSM1818967
GSM1818968
GSM1818969
GSM1818970
GSM1818971
GSM1818972
GSM1818973
GSM1818974
GSM1818975
GSM1818976
GSM1818977
GSM1818978
GSM1818979
GSM1695580
GSM1111754
GSM1111755
GSM605684
GSM605685
GSM605686
GSM605687
GSM736444
GSM736445
GSM736446
GSM1550357
GSM1550358
GSM1550359
GSM1695581
GSM1695582
GSM512880
GSM512881
GSM1054005
GSM1054006
GSM1054007
GSM1054008
GSM1104060
GSM1104061
GSM1104062
GSM1104063
GSM1366702
GSM1366703
GSM1550351
GSM1550352
GSM1550353
GSM1868690
GSM1868691
GSM1868692
GSM1868699
GSM1868700
GSM1868701
GSM1695578
GSM1695579

In [89]:
dfjose['Experiment'].equals(dfsra['Experiment'])

diff_values = dfjose[~dfjose['Experiment'].isin(dfsra['Experiment'])]['Experiment'].unique().tolist()
print(len(diff_values))

df400 = dfjose[dfjose['Experiment'].isin(diff_values)]

408

In [94]:
df400.loc[df400['Ecotype']!='Col-0']

,NameJose,Experiment,SampleName,Tissue,Ecotype,Genotype,Treatment,Project,TotalReads,UniqueMappedRatio,ReleaseDate,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
529,sample03529,GSM1692581,Al_mock_R1,rosette leaf,MN47,--,Mock,PRJNA284487,16493299,0.2275,2015-08-02,abiotic,heat,NaN,NaN,NaN,NaN,NaN,NaN
530,sample03530,GSM1692582,Al_mock_R2,rosette leaf,MN47,--,Mock,PRJNA284487,19272053,0.2328,2015-08-02,abiotic,heat,NaN,NaN,NaN,NaN,NaN,NaN
531,sample03531,GSM1692583,Al_H6_R1,rosette leaf,MN47,--,heat6h,PRJNA284487,13643519,0.1981,2015-08-02,abiotic,heat,NaN,NaN,NaN,NaN,NaN,NaN
532,sample03532,GSM1692584,Al_H6_R2,rosette leaf,MN47,--,heat6h,PRJNA284487,45850200,0.2206,2015-08-02,abiotic,heat,NaN,NaN,NaN,NaN,NaN,NaN
533,sample03533,GSM1692585,Al_H6R48_R1,rosette leaf,MN47,--,heat6hrecovery48h,PRJNA284487,15625259,0.2440,2015-08-02,abiotic,heat,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24488,sample03042,GSM1550353,lyleaves rep3,leaves,lyrata,wild type,--,PRJNA267853,14134623,0.3488,2015-10-13,development,leaves,NaN,NaN,NaN,NaN,NaN,NaN
26242,sample09114,SRX105928,exp7,seedlings,--,--,--,SRP009369,29527875,0.7121,2012-11-17,development,Root Hairs,NaN,NaN,NaN,NaN,NaN,NaN
26243,sample09115,SRX105929,s6,seedlings,--,--,--,SRP009369,45176163,0.6100,2012-11-17,development,Root Hairs,NaN,NaN,NaN,NaN,NaN,NaN
26319,sample03558,GSM1695578,Al_rosette_R1,rosette leaf,Arabidopsis lyrata,--,--,PRJNA284922,19625903,0.2640,2015-08-02,development,rosette leaf,NaN,NaN,NaN,NaN,NaN,NaN
26320,sample03559,GSM1695579,Al_rosette_R2,rosette leaf,Arabidopsis lyrata,--,--,PRJNA284922,18123255,0.2564,2015-08-02,development,rosette leaf,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
#Merge con Web
dfweb.rename(columns={'Unnamed: 0':'BioProject','0':'project_title','1':'project_description','2':'project_biblio'}, inplace = True)
dfsra =  pd.merge(dfsra, dfweb, how='outer', on='BioProject')

#Merge con Info
dfinfo.rename(columns = {'Experiment Accession':'Experiment'}, inplace = True)
dfsra =  pd.merge(dfsra, dfinfo, how='outer', on='Experiment')

In [27]:
dfsra

,Run,ReleaseDate_x,LoadDate,spots,bases,spots_with_mates,avgLength,size_MB,AssemblyName,download_path,...,Sample Accession,Sample Title,"Total Size, Mb",Total RUNs,Total Spots,Total Bases,Library Name,Library Strategy,Library Source,Library Selection
0,SRR21747410,2022-09-28 23:56:36,2022-09-28 23:04:21,42298690.0,2.157233e+09,0.0,51.0,605.0,NaN,https://sra-downloadb.be-md.ncbi.nlm.nih.gov/s...,...,SRS13963792,NaN,605.46,1.0,42298690.0,2.157233e+09,WT_+Fe_1,RNA-Seq,TRANSCRIPTOMIC,other
1,SRR21747384,2022-09-28 23:56:36,2022-09-28 23:00:15,33898232.0,1.728810e+09,0.0,51.0,485.0,NaN,https://sra-downloadb.be-md.ncbi.nlm.nih.gov/s...,...,SRS13963817,NaN,485.65,1.0,33898232.0,1.728810e+09,srf3-3_+Fe_1,RNA-Seq,TRANSCRIPTOMIC,other
2,SRR21747408,2022-09-28 23:56:36,2022-09-28 23:02:09,38579751.0,1.967567e+09,0.0,51.0,551.0,NaN,https://sra-downloadb.be-md.ncbi.nlm.nih.gov/s...,...,SRS13963794,NaN,551.19,1.0,38579751.0,1.967567e+09,srf3-3_+Fe_2,RNA-Seq,TRANSCRIPTOMIC,other
3,SRR21747407,2022-09-28 23:56:36,2022-09-28 23:00:14,30594367.0,1.560313e+09,0.0,51.0,439.0,NaN,https://sra-downloadb.be-md.ncbi.nlm.nih.gov/s...,...,SRS13963795,NaN,439.12,1.0,30594367.0,1.560313e+09,srf3-3_+Fe_3,RNA-Seq,TRANSCRIPTOMIC,other
4,SRR21747406,2022-09-28 23:56:36,2022-09-28 22:59:45,33204289.0,1.693419e+09,0.0,51.0,475.0,NaN,https://sra-downloadb.be-md.ncbi.nlm.nih.gov/s...,...,SRS13963796,NaN,475.61,1.0,33204289.0,1.693419e+09,srf3-3_-Fe_1,RNA-Seq,TRANSCRIPTOMIC,other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108860,SRR22018205,2022-12-13 22:27:24,2022-10-24 02:53:09,26450046.0,7.935014e+09,26450046.0,300.0,2503.0,NaN,https://sra-downloadb.be-md.ncbi.nlm.nih.gov/s...,...,SRS15509568,NaN,2503.87,1.0,26450046.0,7.935014e+09,wosh_20221019_pH 7.5_4,RNA-Seq,TRANSCRIPTOMIC,PolyA
108861,SRR22018204,2022-12-13 22:27:24,2022-10-24 02:39:28,30991602.0,9.297481e+09,30991602.0,300.0,2913.0,NaN,https://sra-downloadb.be-md.ncbi.nlm.nih.gov/s...,...,SRS15509567,NaN,2913.18,1.0,30991602.0,9.297481e+09,wosh_20221019_pH 7.5_6,RNA-Seq,TRANSCRIPTOMIC,PolyA
108862,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,ERS7925674,NaN,NaN,0.0,NaN,NaN,RTB3_p,RNA-Seq,TRANSCRIPTOMIC SINGLE CELL,RANDOM
108863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,ERS7925673,NaN,NaN,0.0,NaN,NaN,RTB1_p,RNA-Seq,TRANSCRIPTOMIC SINGLE CELL,RANDOM
108864,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,SRS7872902,NaN,NaN,0.0,NaN,NaN,NaN,RNA-Seq,TRANSCRIPTOMIC,cDNA

In [28]:
dfsra[dfsra['Run'].isna()]

,Run,ReleaseDate_x,LoadDate,spots,bases,spots_with_mates,avgLength,size_MB,AssemblyName,download_path,...,Sample Accession,Sample Title,"Total Size, Mb",Total RUNs,Total Spots,Total Bases,Library Name,Library Strategy,Library Source,Library Selection
6854,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6855,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6856,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6857,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6858,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21609,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108862,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,ERS7925674,NaN,NaN,0.0,NaN,NaN,RTB3_p,RNA-Seq,TRANSCRIPTOMIC SINGLE CELL,RANDOM
108863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,ERS7925673,NaN,NaN,0.0,NaN,NaN,RTB1_p,RNA-Seq,TRANSCRIPTOMIC SINGLE CELL,RANDOM
108864,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,SRS7872902,NaN,NaN,0.0,NaN,NaN,NaN,RNA-Seq,TRANSCRIPTOMIC,cDNA

# Pruebas

In [23]:
# r = 'GSM.*'
# for index, row in dfenasra.iterrows():
#     re.match(r, row.sample_alias)
#     if r:
#         print("Search successful.")
#     else:
#         print("Search unsuccessful.")

Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.
Search successful.

TypeError: expected string or bytes-like object

In [46]:
dfenasra.loc[dfenasra['run_alias'] =='GSM1835604']

Empty DataFrame
Columns: [Run, ReleaseDate, LoadDate, spots, bases, spots_with_mates, avgLength, size_MB, AssemblyName, download_path, Experiment, LibraryName, LibraryStrategy, LibrarySelection, LibrarySource, LibraryLayout, InsertSize, InsertDev, Platform, Model, SRAStudy, BioProject, Study_Pubmed_id, ProjectID, Sample, BioSample, SampleType, TaxID, ScientificName, SampleName, g1k_pop_code, source, g1k_analysis_group, Subject_ID, Sex, Disease, Tumor, Affection_Status, Analyte_Type, Histological_Type, Body_Site, CenterName, Submission, dbgap_study_accession, Consent, RunHash, ReadHash, accession, experiment_accession, sample_accession, secondary_sample_accession, study_accession, secondary_study_accession, parent_study, submission_accession, run_alias, experiment_alias, sample_alias, study_alias, library_layout, library_selection, library_source, library_strategy, library_name, instrument_model, instrument_platform, base_count, read_count, tax_id, scientific_name, sample_title, experiment_title, study_title, description, sample_description, fastq_md5, fastq_bytes, fastq_ftp, fastq_galaxy, fastq_aspera]
Index: []

[0 rows x 80 columns]

In [31]:
dfsra.loc[dfsra['Run']=='SRR013427']

Empty DataFrame
Columns: [Run, ReleaseDate, LoadDate, spots, bases, spots_with_mates, avgLength, size_MB, AssemblyName, download_path, Experiment, LibraryName, LibraryStrategy, LibrarySelection, LibrarySource, LibraryLayout, InsertSize, InsertDev, Platform, Model, SRAStudy, BioProject, Study_Pubmed_id, ProjectID, Sample, BioSample, SampleType, TaxID, ScientificName, SampleName, g1k_pop_code, source, g1k_analysis_group, Subject_ID, Sex, Disease, Tumor, Affection_Status, Analyte_Type, Histological_Type, Body_Site, CenterName, Submission, dbgap_study_accession, Consent, RunHash, ReadHash]
Index: []

[0 rows x 47 columns]

In [50]:
dfjose.loc[dfjose['Experiment']=='GSM1818909']

,NameJose,Experiment,SampleName,Tissue,Ecotype,Genotype,Treatment,Project,TotalReads,UniqueMappedRatio,ReleaseDate,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
16369,sample03755,GSM1818909,WT.0.1_dexamethasone,seedlings,Col-0,wild type,Mock,PRJNA258547,26432897,0.889,2015-12-16,development,Leaf axial polarity,mutant/Ox,TFs,NaN,NaN,NaN,NaN

In [126]:
gsm_dic.get('GSM1065347')

'SRX217949'

In [ ]:
for index, row in dfjose.iterrows():
    valor = row['Experiment']
    resultado = dfsra.loc[dfsra['SampleName'] == valor, 'Experiment']
    if not resultado.empty:
        print(resultado.iloc[0])
        time.sleep(1)

In [58]:
dfsra.loc[dfsra['SampleName'] == 'GSM1065347', 'Experiment'].iloc[0]

'SRX217949'

In [90]:
for index, row in dfjose.iterrows():
    valor = row['Experiment']
    print(valor)
    dfsra.loc[dfjose['Experiment'][index] == dfsra['SampleName']]['Experiment'].iloc[0]
#     print(result)
    time.sleep(1)

ERX1104197

IndexError: single positional indexer is out-of-bounds

In [87]:
dfjose['Experiment'][345]
dfsra.loc[dfjose['Experiment'][345] == dfsra['SampleName']]['Experiment'].iloc[0]

'SRX217949'